apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
  - name: http-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: fastapi-deployment
